name: Promote app to production

on:
    workflow_dispatch

jobs:
  promote:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Heroku
      run: |
        curl https://cli-assets.heroku.com/install-ubuntu.sh | sh

    - name: Heroku promote app
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: heroku pipelines:promote -a <stg-app-name>

